name: "Tag Version"

author: "mltngpot"

description: "Extracts version number from tag"

outputs:
  full-tag:
    description: "Full Tag"
    value: ${{ runner.os == 'Linux' && steps.get-version.outputs-linux.describe-tag || steps.get-version-windows.outputs.describe-tag }}
  version:
    description: "Version Number: Major.Minor.Patch"
    value: ${{ runner.os == 'Linux' && steps.get-version.outputs-linux.version || steps.get-version-windows.outputs.version }}
  full-version:
    description: "Version Number: Major.Minor.Patch.Build"
    value: ${{ runner.os == 'Linux' && steps.get-version.outputs-linux.full-version || steps.get-version-windows.outputs.full-version }}
  major-version:
    description: "Major Version Number"
    value: ${{ runner.os == 'Linux' && steps.get-version.outputs-linux.major-version || steps.get-version-windows.outputs.major-version }}
  minor-version:
    description: "Minor Version Number"
    value: ${{ runner.os == 'Linux' && steps.get-version.outputs-linux.minor-version || steps.get-version-windows.outputs.minor-version }}
  patch-number:
    description: "Patch Number"
    value: ${{ runner.os == 'Linux' && steps.get-version.outputs-linux.patch-number || steps.get-version-windows.outputs.patch-number }}
  build-number:
    description: "Build Number"
    value: ${{ runner.os == 'Linux' && steps.get-version.outputs-linux.build-number || steps.get-version-windows.outputs.build-number }}

runs:
  using: "composite"
  steps:
    - id: get-version-linux
      run: ${{ github.action_path }}/src/getVersion.sh
      if: runner.os == 'Linux'
      shell: bash      
      
    - id: get-version-windows
      run: ${{ github.action_path }}\src\getVersion.ps1
      if: runner.os == 'Windows'
      shell: pwsh